version: "2"

services:

  web:
    build: .
    ports:
      - "8060:8060"
    links:
      - mongo
    # environment:
    #   - MONGO_URL=mongodb://mongo:27017/heartbeat

  mongo:
    image: mongo
    ports:
      - "27017:27017"